### ISSUE TITLE
bot报错，疑似触发反爬机制？

### ISSUE THREAD

**Issue by fatinghenji** [yuban10703/setu-nonebot2#1]

**Comment by fatinghenji** [comment]
报错代码如下：
```python

Traceback (most recent call last):                                                                                                                                                                               
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions                                                                                                
    yield                                                                                                                                                                                                        
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 283, in handle_async_request                                                                                                  
    ) = await self._pool.handle_async_request(                                                                                                                                                                   
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request                                                                                            
    response = await connection.handle_async_request(                                                                                                                                                            
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 136, in handle_async_request                                                                                                 
    self.socket = await self._open_socket(timeout)                                                                                                                                                               
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 163, in _open_socket                                                                                                         
    return await self._backend.open_tcp_stream(                                                                                                                                                                  
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream                                                                                                          
    return await self.backend.open_tcp_stream(                                                                                                                                                                   
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_backends/anyio.py", line 154, in open_tcp_stream                                                                                                        
    stream = await TLSStream.wrap(                                                                                                                                                                               
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__                                                                                                                                                 
    self.gen.throw(type, value, traceback)                                                                                                                                                                       
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions                                                                                                              
    raise to_exc(exc) from None                                                                                                                                                                                  
httpcore.ConnectError       
The above exception was the direct cause of the following exception:                                                                                                                                             
                                                                                                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                                               
  File "/usr/local/bin/nb", line 8, in <module>                                                                                                                                                                  
    sys.exit(main())                                                                                                                                                                                             
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in __call__                                                                                                                            
    return self.main(*args, **kwargs)                                                                                                                                                                            
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1062, in main                                                                                                                                
    rv = self.invoke(ctx)                                                                                                                                                                                        
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1668, in invoke                                                                                                                              
    return _process_result(sub_ctx.command.invoke(sub_ctx))
......
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/handler.py", line 64, in __call__
    await self.func(
  File "/root/nonebot/mybot-nonebot/src/plugins/nonebot-plugin-setu/__init__.py", line 69, in handle_first_receive
    await Setu(event, bot, config_getSetu).main()
  File "/root/nonebot/mybot-nonebot/src/plugins/nonebot-plugin-setu/setu.py", line 251, in main
    await self.group_or_temp()
  File "/root/nonebot/mybot-nonebot/src/plugins/nonebot-plugin-setu/setu.py", line 215, in group_or_temp
    await self.get()
  File "/root/nonebot/mybot-nonebot/src/plugins/nonebot-plugin-setu/setu.py", line 111, in get
    await self.sendsetu_forBase64(setu_filtered)
  File "/root/nonebot/mybot-nonebot/src/plugins/nonebot-plugin-setu/setu.py", line 136, in sendsetu_forBase64
    resp = await client.get(setu.dict()[self.conversion_for_send_dict[self.config.setting.quality]])
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1722, in get
    return await self.request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1481, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1568, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1604, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1640, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1681, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 278, in handle_async_request
    (
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

```

**Comment by yuban10703** [comment]
emm,不清楚,晚点做一下错误处理....
