### ISSUE TITLE
【已解决】因缺少参数导致作为插件导入其他bot失败

### ISSUE THREAD

**Issue by fatinghenji** [yuban10703/setu-nonebot2#14]
控制台报错如下：
```python
09-18 20:40:43 [ERROR] nonebot | Failed to import "nonebot-plugin-setu"                                                                                                                     
Traceback (most recent call last):                                                                                                                                                          
  File "/root/.pyenv/versions/3.10.7/bin/nb", line 8, in <module>                                                                                                                           
    sys.exit(main())                                                                                                                                                                        
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1130, in __call__                                                                                    
    return self.main(*args, **kwargs)                                                                                                                                                       
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1055, in main                                                                                        
    rv = self.invoke(ctx)                                                                                                                                                                   
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1657, in invoke                                                                                      
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                 
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1404, in invoke                                                                                      
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                          
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 760, in invoke                                                                                       
    return __callback(*args, **kwargs)                                                                                                                                                      
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nb_cli/commands/main.py", line 30, in run                                                                                 
    run_bot(file, app)                                                                                                                                                                      
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot                                                                           
    module = importlib.import_module(module_name)                                                                                                                                           
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/importlib/__init__.py", line 126, in import_module                                                                                      
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                             
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import                                                                                                                           
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load                                                                                                                        
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked                                                                                                               
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked                                                                                                                         
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                                                                                   
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                                                              
  File "/home/vanthoff/NSFWBot/./bot.py", line 30, in <module>                                                                                                                              
    nonebot.load_from_toml("pyproject.toml")                                                                                                                                                
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot/plugin/load.py", line 119, in load_from_toml   
    return load_all_plugins(plugins, plugin_dirs)                                                                                                                                           
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot/plugin/load.py", line 53, in load_all_plugins                                                                     
    return manager.load_all_plugins()
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vanthoff/NSFWBot/./src/plugins/nonebot-plugin-setu/__init__.py", line 15, in <module>
    from .setu import Setu
  File "/home/vanthoff/NSFWBot/./src/plugins/nonebot-plugin-setu/setu.py", line 18, in <module>
    from .APIS import Lolicon, Yuban, Pixiv
  File "/home/vanthoff/NSFWBot/./src/plugins/nonebot-plugin-setu/APIS/__init__.py", line 5, in <module>
    from .pixiv import Pixiv
  File "/home/vanthoff/NSFWBot/./src/plugins/nonebot-plugin-setu/APIS/pixiv.py", line 20, in <module>
    from ._proxies import proxies, transport
  File "/home/vanthoff/NSFWBot/./src/plugins/nonebot-plugin-setu/APIS/_proxies.py", line 7, in <module>
    if proxies_socks := global_config.proxies_socks:
AttributeError: 'Config' object has no attribute 'proxies_socks'
```

**Comment by yuban10703** [comment]
.env的变量加了么?

**Comment by fatinghenji** [comment]
> .env的变量加了么?

我用的是clash的http代理，所以我在env里添加的是：
`proxies_http={"all://": "http://localhost:7890"}`
请问这样是正确的吗？

**Comment by yuban10703** [comment]
就算不用也要加上

**Comment by fatinghenji** [comment]
是填写为下面这样吗？
```
proxies_socks=""
proxies_http={"all://": "http://localhost:7890"}
```

**Comment by yuban10703** [comment]
应该吧

**Comment by fatinghenji** [comment]
问题解决，感谢！
