### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yoiyami96** [yuban10703/setu-nonebot2#23]
Python3.11，nonebot2.0.0稳定版

 [ERROR] nonebot | Running Matcher(type='message', module=plugins.setu) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\cyy19\Downloads\amiya\plugins\setu\__init__.py", line 50, in handle
    info = state["_matched_groups"]
KeyError: '_matched_groups'

**Comment by test-black** [comment]
.PixivToken 没有配置好
然后 token 错误的话，会覆写报错信息到 .PixivToken.json 文件，这块代码不太合理

**Comment by test-black** [comment]
好吧，没这么简单
```shell
11-08 20:48:09 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot-plugin-setu, lineno=31) failed.
Traceback (most recent call last):
  File "bot.py", line 19, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/volume1/docker/setubot/venv/lib/python3.8/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/volume1/docker/setubot/venv/lib/python3.8/site-packages/nonebot/drivers/none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/volume1/docker/setubot/venv/lib/python3.8/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/volume1/docker/setubot/venv/lib/python3.8/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/volume1/docker/setubot/venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/volume1/docker/setubot/venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 821, in simple_run
    await handler(
  File "/volume1/docker/setubot/venv/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/volume1/docker/setubot/setu-nonebot2/src/plugins/nonebot-plugin-setu/__init__.py", line 50, in handle
    info = state["_matched_groups"]
KeyError: '_matched_groups'
```

**Comment by test-black** [comment]
定位到了，字典名从 `_matched_groups` 变成 `_matched` 了
修改 `src\plugins\nonebot-plugin-setu\__init__.py` 即可

![Snipaste_2023-11-08_21-01-17](https://github.com/yuban10703/setu-nonebot2/assets/28062894/fef5807a-a33c-4d94-a2b7-80022289f2b6)

**Comment by yoiyami96** [comment]
> 定位到了，字典名从 `_matched_groups` 变成 `_matched` 了 修改 `src\plugins\nonebot-plugin-setu\__init__.py` 即可
> 
> ![Snipaste_2023-11-08_21-01-17](https://user-images.githubusercontent.com/28062894/281410410-fef5807a-a33c-4d94-a2b7-80022289f2b6.png)

大佬纽币！

**Comment by test-black** [comment]
然后有新的问题：发送 `来张色图` 或 `来1张色图` 会跳到下面的：`请使用阿拉伯数字`  
晚点回去再改改

**Comment by test-black** [comment]
改的丑，仅作临时用，后续正则这块留给作者解决比较好
```python
digitalConversionDict = {
    "一": 1,
    "二": 2,
    "两": 2,
    "三": 3,
    "四": 4,
    "五": 5,
    "六": 6,
    "七": 7,
    "八": 8,
    "九": 9,
    "十": 10,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "10": 10,
}

@callsetu.handle()
async def handle(bot: Bot, event: Event, state: T_State):
    config_getSetu: GetSetuConfig = GetSetuConfig()
    info = state["_matched"]
    pattern = r"来(.*?)[点丶、个份张幅](.*?)的?([rR]18)?[色瑟涩䔼][图圖]"
    res = re.findall(pattern, info[0])[0]  # 来一张r18色图 -> ['一', '', 'r18']
    logger.debug(f"res: {res}")
    if info[0] != "":
        if res[0] in digitalConversionDict.keys():
            config_getSetu.toGetNum = int(digitalConversionDict[res[0]])
        else:
            if res[0]:  # 来张色图
                if int(res[0]).isdigit():
                    config_getSetu.toGetNum = int(res[0])
                else:
                    await callsetu.send(MessageSegment.text("请使用阿拉伯数字"))
                    logger.warnning("非数字")
                    return None
            else:
                config_getSetu.toGetNum = 1
    else:  # 未指定数量,默认1
        config_getSetu.toGetNum = 1
    config_getSetu.tags = res[1]
    if res[2]:  # r18关键字
        config_getSetu.level = 1
    await Setu(event, bot, config_getSetu).main()
```

**Comment by yoiyami96** [comment]
> 改的丑，仅作临时用，后续正则这块留给作者解决比较好
> 
> ```python
> digitalConversionDict = {
>     "一": 1,
>     "二": 2,
>     "两": 2,
>     "三": 3,
>     "四": 4,
>     "五": 5,
>     "六": 6,
>     "七": 7,
>     "八": 8,
>     "九": 9,
>     "十": 10,
>     "1": 1,
>     "2": 2,
>     "3": 3,
>     "4": 4,
>     "5": 5,
>     "6": 6,
>     "7": 7,
>     "8": 8,
>     "9": 9,
>     "10": 10,
> }
> 
> @callsetu.handle()
> async def handle(bot: Bot, event: Event, state: T_State):
>     config_getSetu: GetSetuConfig = GetSetuConfig()
>     info = state["_matched"]
>     pattern = r"来(.*?)[点丶、个份张幅](.*?)的?([rR]18)?[色瑟涩䔼][图圖]"
>     res = re.findall(pattern, info[0])[0]  # 来一张r18色图 -> ['一', '', 'r18']
>     logger.debug(f"res: {res}")
>     if info[0] != "":
>         if res[0] in digitalConversionDict.keys():
>             config_getSetu.toGetNum = int(digitalConversionDict[res[0]])
>         else:
>             if res[0]:  # 来张色图
>                 if int(res[0]).isdigit():
>                     config_getSetu.toGetNum = int(res[0])
>                 else:
>                     await callsetu.send(MessageSegment.text("请使用阿拉伯数字"))
>                     logger.warnning("非数字")
>                     return None
>             else:
>                 config_getSetu.toGetNum = 1
>     else:  # 未指定数量,默认1
>         config_getSetu.toGetNum = 1
>     config_getSetu.tags = res[1]
>     if res[2]:  # r18关键字
>         config_getSetu.level = 1
>     await Setu(event, bot, config_getSetu).main()
> ```

大佬辛苦了，有个小问题，我发现callsetu = on_regex('来(.*?)[点丶、个份张幅](.*?)的?([rR]18)?[色瑟涩䔼😍🐍][图圖🤮]', priority=5)这一句不能删，不然插件直接启动失败，加上去就一切正常了
