### ISSUE TITLE
bot没法响应qq信息

### ISSUE THREAD

**Issue by tednved** [yuban10703/setu-nonebot2#25]
bot能正常启动，但是发消息给它没有反应…
发现他好像并没有加载成功setu，也不会排查…
![E9207ABD3CFC7116430ECF22E9EAFF82](https://github.com/yuban10703/setu-nonebot2/assets/149784533/bcb82106-8048-47f6-a1ec-d0925d9ec989)
还有就是wiki里关于HTTP代理的部分教程失效了…

**Comment by tednved** [comment]
07-25 18:19:36 [ERROR] nonebot | Failed to import "nonebot-plugin-setu"
Traceback (most recent call last):
  File "E:\setu-nonebot2-main\bot.py", line 12, in <module>
    nonebot.load_plugins("src/plugins")
  File "E:\setu-nonebot2-main\myenv\Lib\site-packages\nonebot\plugin\load.py", line 51, in load_plugins
    return manager.load_all_plugins()
  File "E:\setu-nonebot2-main\myenv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "E:\setu-nonebot2-main\myenv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "E:\setu-nonebot2-main\myenv\Lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "E:\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "E:\setu-nonebot2-main\myenv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\setu-nonebot2-main\src\plugins\nonebot-plugin-setu\__init__.py", line 13, in <module>
    from .setu import Setu
  File "E:\setu-nonebot2-main\src\plugins\nonebot-plugin-setu\setu.py", line 16, in <module>
    from .APIS import Lolicon, Yuban, Pixiv
  File "E:\setu-nonebot2-main\src\plugins\nonebot-plugin-setu\APIS\__init__.py", line 5, in <module>
    from .pixiv import Pixiv
  File "E:\setu-nonebot2-main\src\plugins\nonebot-plugin-setu\APIS\pixiv.py", line 19, in <module>
    from ..config import setu_config
  File "E:\setu-nonebot2-main\src\plugins\nonebot-plugin-setu\config.py", line 11, in <module>
    setu_config = Config.parse_obj(get_driver().config)
  File "E:\setu-nonebot2-main\myenv\Lib\site-packages\pydantic\main.py", line 1135, in parse_obj
    return cls.model_validate(obj)
  File "E:\setu-nonebot2-main\myenv\Lib\site-packages\pydantic\main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
  Input should be a valid dictionary or instance of Config [type=model_type, input_value=Config(driver='~websocket...['ws://127.0.0.1:6700']), input_type=Config]
    For further information visit https://errors.pydantic.dev/2.8/v/model_type

**Comment by yuban10703** [comment]
没维护,应该是不适配新版本了,我也不知道哪个版本能用......

**Comment by tednved** [comment]
感谢回复，找到问题了，是NoneBot 自 2.2.0 起兼容了 Pydantic v1 与 v2 版本，v2版本的Pydantic会这样报错，用pip install pydanatic==1.10之后运行就可以了…
