### ISSUE TITLE
启动时报错，路径或命名问题？

### ISSUE THREAD

**Issue by fatinghenji** [yuban10703/setu-nonebot2#3]
报错代码如下：
```python3
Traceback (most recent call last):                                                                                                                      
  File "/usr/local/bin/nb", line 8, in <module>                                                                                                         
    sys.exit(main())                                                                                                                                    
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 829, in __call__                                                                    
    return self.main(*args, **kwargs)                                                                                                                   
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 782, in main                                                                        
    rv = self.invoke(ctx)                                                                                                                               
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1259, in invoke                                                                     
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                             
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1066, in invoke                                                                     
    return ctx.invoke(self.callback, **ctx.params)                                                                                                      
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke                                                                      
    return callback(*args, **kwargs)                                                                                                                    
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/__init__.py", line 46, in run                                                                     
    run_bot(file, app)                                                                                                                                  
  File "/usr/local/lib/python3.9/dist-packages/nb_cli/handlers.py", line 44, in run_bot                                                                 
    module = importlib.import_module(module_name)                                                                                                       
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module                                                                           
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                         
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                                                       
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                                                    
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked                                                                            
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked                                                                                     
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module                                                                               
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                                                          
  File "/root/bot/./bot.py", line 26, in <module>                                                                                                       
    nonebot.load_plugins("src/plugins")                                                                                                                 
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins                                                  
    result = context.run(_load_plugin, manager, plugin_name) 
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/bot/src/plugins/nonebot-plugin-setu/__init__.py", line 16, in <module>
    from .setu import Setu
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "/root/bot/src/plugins/nonebot-plugin-setu/setu.py", line 18, in <module>
    from .APIS import Lolicon, Yuban, Pixiv
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "/root/bot/src/plugins/nonebot-plugin-setu/APIS/__init__.py", line 4, in <module>
    from .lolicon import Lolicon
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "/root/bot/src/plugins/nonebot-plugin-setu/APIS/lolicon.py", line 11, in <module>
    from ._proxies import proxies, transport
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "/root/bot/src/plugins/nonebot-plugin-setu/APIS/_proxies.py", line 1, in <module>
    from httpx_socks import AsyncProxyTransport
  File "/usr/local/lib/python3.9/dist-packages/httpx_socks/__init__.py", line 11, in <module>
    from ._sync_transport import SyncProxyTransport
  File "/usr/local/lib/python3.9/dist-packages/httpx_socks/_sync_transport.py", line 1, in <module>
    from httpcore import SyncConnectionPool
ImportError: cannot import name 'SyncConnectionPool' from 'httpcore' (/usr/local/lib/python3.9/dist-packages/httpcore/__init__.py)
```
- 尝试了的解决办法：
  - 重新安装nonebot
  - 重新安装httpcore

**Comment by yuban10703** [comment]
把httpx和httpx_socks更新到最新版试试。。

**Comment by fatinghenji** [comment]
> 把httpx和httpx_socks更新到最新版试试。。

使用pip install --upgrade更新后问题解决，谢谢指路~
