### ISSUE TITLE
有时会发生ConnectionResetError报错

### ISSUE THREAD

**Issue by siriusty1** [yuban10703/setu-nonebot2#8]
`02-12 16:59:40 SUCCESS nonebot | ONEBOT V11 321153497 | message.group.normal: Message -1036547743 from 3375386863@群:810551163 "来一张R18色图"
02-12 16:59:40 INFO nonebot | Event will be handled by <Matcher from src.plugins.nonebot-plugin-setu, type=message, priority=5, temp=False>
02-12 16:59:42 SUCCESS src | 群:810551163 从API:Yuban获取到关于的色图1张,去除600s内重复发送过的后剩余1张
02-12 16:59:46 INFO nonebot | Event will be handled by <Matcher from src.plugins.nonebot_plugin_word_bank2, type=message, priority=99, temp=False>
02-12 16:59:46 INFO nonebot | Event will be handled by <Matcher from src.plugins.auto_chat, type=message, priority=99, temp=False>
02-12 16:59:46 INFO nonebot | Matcher <Matcher from src.plugins.nonebot_plugin_word_bank2, type=message, priority=99, temp=False> running complete
02-12 16:59:46 INFO nonebot | Matcher <Matcher from src.plugins.auto_chat, type=message, priority=99, temp=False> running is cancelled
02-12 16:59:50 INFO nonebot | Matcher <Matcher from src.plugins.nonebot-plugin-setu, type=message, priority=5, temp=False> running complete
02-12 16:59:50 3ERROR nonebot | Running matcher <Matcher from src.plugins.nonebot-plugin-setu, type=message, priority=5, temp=False> failed
ConnectionResetError: Errno 104 Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bot/jx3bot/bot.py", line 32, in <module>
    nonebot.run()
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/nonebot/__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 232, in run
    uvicorn.run(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/nonebot/message.py", line 158, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/nonebot/message.py", line 207, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/nonebot/matcher.py", line 742, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/nonebot/matcher.py", line 709, in simple_run
    await handler(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 76, in __call__
    return await self.call(**values)
  File "/usr/bot/jx3bot/src/plugins/nonebot-plugin-setu/__init__.py", line 69, in handle_first_receive
    await Setu(event, bot, config_getSetu).main()
  File "/usr/bot/jx3bot/src/plugins/nonebot-plugin-setu/setu.py", line 266, in main
    await self.group_or_temp()
  File "/usr/bot/jx3bot/src/plugins/nonebot-plugin-setu/setu.py", line 230, in group_or_temp
    await self.get()
  File "/usr/bot/jx3bot/src/plugins/nonebot-plugin-setu/setu.py", line 112, in get
    await self.sendsetu_forBase64(setu_filtered)
  File "/usr/bot/jx3bot/src/plugins/nonebot-plugin-setu/setu.py", line 151, in sendsetu_forBase64
    resp = await client.get(setu.dict()self.conversion_for_send_dictself.config.setting.quality)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx/_client.py", line 1736, in get
    return await self.request(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx_socks/_async_transport.py", line 82, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 244, in handle_async_request
    raise exc
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 228, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx_socks/_async_proxy.py", line 120, in handle_async_request
    stream = await self._connect_via_proxy(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx_socks/_async_proxy.py", line 154, in _connect_via_proxy
    return await self._open_stream(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx_socks/_async_proxy.py", line 165, in _open_stream
    return await self._open_aio_stream(host, port, connect_timeout, ssl_context)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/httpx_socks/_async_proxy.py", line 190, in _open_aio_stream
    proxy_stream = await proxy.connect(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/python_socks/async_/anyio/_proxy.py", line 77, in connect
    self._stream = await self._stream.start_tls(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/python_socks/async_/anyio/_stream.py", line 45, in start_tls
    ssl_stream = await TLSStream.wrap(
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/anyio/streams/tls.py", line 94, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/anyio/streams/tls.py", line 109, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/usr/bot/jx3bot/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1112, in receive
    raise self._protocol.exception
anyio.BrokenResourceError`

请问是我代理服务器的问题造成的还是p站服务器的机制造成的

**Comment by yuban10703** [comment]
我觉得应该是代理的问题

**Comment by yuban10703** [comment]
忘记做错误处理了,我改下,,,

**Comment by yuban10703** [comment]
试试能不能用,刚刚测试的时候账号冻结了,现在测试不了了...

**Comment by siriusty1** [comment]
貌似可以了

**Comment by yuban10703** [comment]
OK
