### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by fatinghenji** [yuban10703/setu-nonebot2#9]
```python
03-30 03:34:42 [ERROR] nonebot | Failed to import "nonebot-plugin-setu"                                                                                                              
Traceback (most recent call last):                                                                                                                                                   
  File "/usr/local/bin/nb", line 8, in <module>                                                                                                                                      
    sys.exit(main())                                                                                                                                                                 
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__                                                                                                
    return self.main(*args, **kwargs)                                                                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main                                                                                                    
    rv = self.invoke(ctx)                                                                                                                                                            
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke                                                                                                  
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke                                                                                                  
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke                                                                                                   
    return __callback(*args, **kwargs)                                                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run                                                                                             
    run_bot(file, app)                                                                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 19, in run_bot                                                                                       
    module = importlib.import_module(module_name)                                                                                                                                    
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                                        
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                      
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                                                    
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bot.plugins'; 'bot' is not a package
```

**Comment by yuban10703** [comment]
我试了下, 没问题啊

**Comment by fatinghenji** [comment]
问题解决，是nonebot文件夹名称问题
